CREATE DATABASE TASK6;
USE TASK6 ;
CREATE TABLE EMPLOYEES(
	ID INT PRIMARY KEY,
    NAME VARCHAR(50),
    DEPARTMENT VARCHAR(50),
    SALARY INT
);

INSERT INTO EMPLOYEES VALUES
(1,'ANAMIKA','IT',600000),
(2,'RAVI','HR',50000),
(3,'SNEHA','IT',70000),
(4,'AMIT','FINANCE',55000),
(5,'PRIYA','IT',65000);

-- 1. SUBQUERY IN WHERE CLAUSE

SELECT NAME 
FROM EMPLOYEES
WHERE SALARY > (SELECT AVG (SALARY) FROM EMPLOYEES);

-- 2. SCALAR SUBQUERY IN SELECT

SELECT NAME,
	(SELECT MAX(SALARY) FROM EMPLOYEES) AS HIHGEST_SALARY
    FROM EMPLOYEES;
    
-- 3. SUBQUERY IN FROM CLAUSE (DERIVED TABLE)

SELECT DEPARTMENT, AVG_SALARY
FROM(
	SELECT DEPARTMENT, AVG(SALARY) AS AVG_SALARY
    FROM EMPLOYEES
    GROUP BY DEPARTMENT)
    AS  DEPT_AVG;

-- 4. CORRELATED SUBQUERY 

SELECT NAME , SALARY 
FROM EMPLOYEES e1
WHERE SALARY > (
	SELECT AVG(SALARY)
    FROM EMPLOYEES e2
    WHERE e2.DEPARTMENT = e1.DEPARTMENT
);


-- 5. USING EXISTS

SELECT NAME 
FROM EMPLOYEES e
WHERE EXISTS(
SELECT 1 FROM EMPLOYEES
WHERE DEPARTMENT = 'IT' AND SALARY > 600000
);